dataset: 'tumcamp'
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: False
  const_speed_assumption: True
  # lr: 0.0005
  lr: 0.002    
  # pixels: 1000
  pixels: 5000
  iters: 50
mapping:
  every_frame: 5
  vis_freq: 50
  vis_inside_freq: 30
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 10
  pixels: 5000
  iters_first: 1500
  iters: 60
cam: 
  H: 913 
  W: 1138
  fx: 702.0629882812500000
  fy: 701.9381713867187500
  cx: 572.2602127578575164
  cy: 436.6439347957930295
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 0